### ISSUE TITLE
Built with JIgsaw - imaje.photo

### ISSUE THREAD

**Issue by imaje89** [tighten/builtwithjigsaw#172]
Hey Developers, 

Just flagging this here as per the site instructions, I'm very proud to have released my personal photography and personal UX designer website using jigsaw :) 

[Imaje.photo](https://imaje.photo)
![image](https://github.com/tighten/builtwithjigsaw/assets/2320129/3a71163b-3e4a-460a-96d1-4ce70f71ec04)

[Imaje.co.uk](https://imaje.co.uk)
![image](https://github.com/tighten/builtwithjigsaw/assets/2320129/748bb7e7-bd68-4f47-94b6-da37ba959ea5)

Thank you for developing such an awesome product and your consideration :)

**Comment by mateusjunges** [comment]
@imaje89 thanks for sharing! If you'd like, feel free to open a PR to submit your sites to https://builtwithjigsaw.com. You can find the instructions on how to do that on the [README](https://github.com/tighten/builtwithjigsaw/blob/main/readme.md).

Keep up the great work!
